<div id="owl-one" class="owl-carousel owl-theme">
    <div class="item">
        <img src="http://localhost:8080/media/wysiwyg/slide_1.jpg" alt="Slide 1" />
    </div>
    <div class="item">
        <img src="http://localhost:8080/media/wysiwyg/slide_1.jpg" alt="Slide 2" />
    </div>
</div>

<script>
    require([
        'jquery', 
        'owlcarousel'
    ], function ($) {
        $(document).ready(function () {
            $('#owl-one').owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                responsive: {
                    0: {
                        items: 1,
                        nav: false
                    },
                    600: {
                        items: 1,
                        nav: false
                    },
                    1000: {
                        items: 1,
                        nav: true
                    }
                }
            });
        });
    });
</script>